### PR TITLE
Try turning coverage checking back on

### PR DESCRIPTION
**Pull request by patricksnape**
This should only upload coverage for travis - which is all
we want really.

### CODE REVIEW

**Comment by patricksnape** [comment]
jenkins retest this please

**Comment by patricksnape** [comment]
@jabooth this works - can I merge?

**Comment by jabooth** [comment]
@patricksnape can we test that test failures still correctly fail CI checks with this change? Just that I seem to remember we moved to `run_test.py` as we were experiencing a nasty bug with silent failures (although my memory is hazy).

**Comment by jabooth** [comment]
https://github.com/menpo/menpo/commit/4f3c39485d814169e720c4bb1c7f367a25e7008b was the hotfix in question, I misremembered, was an issue within `run_test.py`. @patricksnape if you are confident that tests will still fail, +1.

**Comment by patricksnape** [comment]
You want me to add a failing test, then remove it to show that?

**Comment by patricksnape** [comment]
@jabooth Happy with those failures?

**Comment by patricksnape** [comment]
You saw it! Force pushed away!

**Comment by jabooth** [comment]
You failed beautifully :+1: 

+1

**Pull request merged**
