### PR TITLE
Channels flip

### PR DESCRIPTION
**Pull request by jalabort**
This pull request moves the channel axis in `menpo` `Image` (and subclasses) from the very back to the very front. That is,  images are now defined to have shape `(n_channels, X, Y, ...)` instead of `(X, Y, ..., n_channels)`

- This change allows for a much faster gradient computation, specially in the case of 2-dimensional multichannel images.
- The previous should, in turn, lead to faster feature computation (for those features needing to compute gradients) and much faster AAMs in `menpofit`.

> As an example, in my machine, the gradient computation of an old `menpo` `Image` of shape (206, 213, 36) took ~ 55ms.  The gradient computation of the equivalent `menpo` `Image` with the channels at the front (36, 206, 213) takes now ~17ms.  

- [x] Agree on whether the method `gradient` on image is kept or removed. 

> Upon discussion: the `gradient` method will be removed from `Image`. A new method called `set_boundary_pixels` will be introduced which can be called after computing the gradient of `MaskedImage` in order to remove ill-defined boundary pixels along the mask.

- [x] Adapt IGO, ES and Daisy.

> Test were updated due to numerical difference between the fast cython 'gradient' and the numpy 'gradient' which lead to slightly different results for the three previous features.

- [x] Adapt HOGs, LBPS and Glyph.

> Note that all test pass. However, HOGs, LBPs and Glyph are only naively adapted to the new image shapes by moving the channel axis to the back. Ideally, these changes should be done in a separate pull request so that this one can be merged in asap .

### CODE REVIEW

**Comment by jalabort** [comment]
@patricksnape has found some very nasty bugs on the `gradient` feature. He will correct them throughout the upcoming days. Until then this cannot be merged in.

**Comment by jabooth** [comment]
I've merged this in with master and gone through and tidied up the slicing a little (`a[2, ...] == a[2]`). At this point I'm happy to get this in. There are probably some small bugs but I think we are best getting people using this so we find them before we start thinking about the 0.5.0 release. +1

**Comment by patricksnape** [comment]
[This post](http://www.google.com/url?q=http%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Finternals.html&sa=D&sntz=1&usg=AFQjCNHHqrAhNNp0lejIJnzVyDDPMX1_Yw) on Numpy has some nice explanations of the logic for the channel flip (and our default image ordering)

**Comment by nontas** [comment]
After testing this branch (and after the bug fixes done by @patricksnape ) I think this is ready.
+1

**Comment by patricksnape** [comment]
I'm preferring to be bold when it comes to this PR. I'm going to merge it in this afternoon unless anyone has a good reason not to. +1

**Comment by jalabort** [comment]
+1

**Pull request merged**
