### PR TITLE
Add mirroring check to procrustes

### PR DESCRIPTION
**Pull request by patricksnape**
By default, do not allow mirroring for procrustes by guaranteeing
that the rotation matrix is positive.

### CODE REVIEW

**Comment by jabooth** [comment]
Great! A test for with/without mirroring would be great - maybe just align two point clouds of four points, one being (0, 0), (1, 0), (1, 1), (0, 1). Construct the other with corners flipped so a mirror gives a perfect fit, test with/without?

**Comment by jabooth** [comment]
@patricksnape would be really good to add this, just needs tests and manual merge

**Comment by jabooth** [comment]
@menpobot test this please

**Comment by nontas** [comment]
I added the `allow_mirror` argument to the `AlignmentRotation`, `AlignmentSimilarity`, and `GeneralizedProcrustesAnalysis` classes, as well as the `procrustes_alignment` method.

It's default value is set to ``False``, which broke 3 Procrustes related tests. Finally, I added an `AlignmentRotation` test to check the mirroring behaviour.

**Comment by patricksnape** [comment]
menpobot is just failing to pick up the re-run test - [it's passing](http://jenkins.menpo.org/job/menpo-pr/53/)

**Comment by patricksnape** [comment]
+1 test is added and failed tests are fixed

**Pull request merged**
