### PR TITLE
Fix negative values in HOG calculation

### PR DESCRIPTION
**Pull request by patricksnape**
Values were not being rounded correctly due to truncation
of the interger cell size in pixels. This corrects that
by using the original code used by @nontas in Matlab.

### CODE REVIEW

**Comment by patricksnape** [comment]
This segfaults... Needs more investigaton - **do not merge**.

**Comment by patricksnape** [comment]
No longer segfaults - but now I question it's validity. I think we should look at totally replacing the HOG code :(

**Comment by patricksnape** [comment]
In general, I have not investigated the correctness of this branch - however - there are so many implementations of HOG anyway that I don't think this really hurts. From what I've seen this doesn't affect fitting performance at all and it *stops a potential segfault*. Thoughts on just merging this and then coming back to re-implementing HOG/LBP in the future @jabooth?

**Comment by patricksnape** [comment]
@jalabort said he used this branch and thought the results seemed OK. I'm leaning towards merging this in for the next release to stop the wrong behaviour?

**Comment by jalabort** [comment]
Yeah, I've been using this for a while and haven't had issues with it

**Pull request merged**
