### PR TITLE
Rasterize 2D Landmarks Method

### PR DESCRIPTION
**Pull request by patricksnape**
This method allows rasterizing of landmark groups onto an image.
Multiple landmark groups can be rasterized onto the same
image for efficiency. Currently two backends are provided, pillow
and matplotlib. The matplotlib backend is far more feature
complete, but slow! The pillow backend is much simpler but
an order of magnitude faster than the matplotlib backend.

@nontas check this out - it should be something you will like :smile:

### CODE REVIEW

**Comment by nontas** [comment]
That looks great @patricksnape !! 
My only comment is that since this PR replaces `plt.scatter` with `plt.plot` for rendering points (and also correctly changes `marker_size` default value from ``20`` to ``5``), we should also change the `marker_size` documentation in our viewable classes (e.g. `Image`, `PointCloud`, `PointGraph` etc.). `marker_size` is no longer `The size of the markers in points^2.` but `The size of the markers in points.`

**Comment by nontas** [comment]
+1

**Comment by patricksnape** [comment]
@jabooth Want to check this too?

**Comment by jabooth** [comment]
Works well! Only comment is that I think a fairly likely that users may wish to render all landmarks out, and atm that would require something like: 
```py
img.rasterize_landmarks_2d(group=img.landmarks.keys())
```
Saying that, in such cases you would need to know what order the keys are in to choose different colours etc for the landmarks. The API chosen here is consistent with what we have elsewhere in menpo, so let's get this in.

+1

**Pull request merged**
