### PR TITLE
new print_progress visualization function

### PR DESCRIPTION
**Pull request by jabooth**
new convenience function for reporting on the time remaining for processing an iterator. Saves you manually calling `print_dynamic()` and `progress_bar_str()`

This for loop:

```python
from time import sleep
for i in print_progress(range(10)):
    sleep(1)
```
prints a progress report of the form:
```
[=============       ] 70% (7/10) 00:00:03 remaining
```

### CODE REVIEW

**Comment by patricksnape** [comment]
This looks super ace +1

**Comment by nontas** [comment]
Amazing addition! +1

**Comment by jalabort** [comment]
Indeed this is super cool!

**Comment by jalabort** [comment]
+1

**Pull request merged**
