### PR TITLE
rescale_pixels() for rescaling the range of pixels

### PR DESCRIPTION
**Pull request by jabooth**
Adds a new method to Images that makes it easy to linearly rescale the range of pixels to a certain range. The range is given by a maximum and minimum value. The user can choose whether the scaling should be performed per channel independently, or for all pixels in the image across channels.

### CODE REVIEW

**Comment by jabooth** [comment]
[tests to come, just wanted to post this before it was forgotten]

**Comment by patricksnape** [comment]
A test? And then I will +1

**Comment by nontas** [comment]
Nice addition! +1

**Comment by jabooth** [comment]
@patricksnape added tests, let me know if you are happy after the travis run

**Pull request merged**
