### PR TITLE
Visualization and Widgets upgrade

### PR DESCRIPTION
**Pull request by nontas**
This PR makes several improvements and additions to the visualization of menpo's objects, to the widgets and to the documentation. Specifically:

### Visualization
* **view()**: The `view()` methods of all objects (`Image`, `MaskedImage`, `PointCloud`, `PointGraph`, `TriMesh`, `LandmarkGroup`, `LandmarkManager`) as well as the `view_landmarks()` method of `Image` and `MaskedImage` have a set of arguments related to their rendering. Depending on each objects, these arguments define options related to the _lines_, _markers_, _numbering_, _legend_, _axes_ and _figure_. These options are defined in the renderers (`menpo.visualize.viewmatplotlib.py`), i.e. `MatplotlibImageViewer2d`, `MatplotlibPointGraphViewer2d`, `MatplotlibLandmarkViewer2d`.
* **view_widget()**: All menpo objects (`Image`, `MaskedImage`, `PointCloud`, `PointGraph`, `TriMesh`, `LandmarkGroup`, `LandmarkManager`) also have a `view_widget()` method. The method takes as argument `popup : bool`, which defines whether to open up the widget as a pop-up window.
* **save_figure(), save_figure_widget()**: All renderers have a `save_figure()` method for saving the figure to file. The method is defined in `MatplotlibRenderer` and can be used like:
```
viewer = image.view()
viewer.save_figure('/home/user/image.png', format='png', overwrite=True)
```
The method has a smart logic for checking the path, thanks to @patricksnape . The renderers also have a `save_figure_widget()` method.
* **plot_eigenvalues(), plot_eigenvalues_ratio(), plot_eigenvalues_cumulative_ratio()**: The `PCAModel` class now has those three plotting methods. They all use `GraphPlotter` class (which utilizes `MatplotlibGraphPlotter` that is now upgraded in order to get rendering options related to the _lines_, _markers_, _legend_, _axes_, _grid_ and _figure_.

### Widgets
The logic behind most widgets is now updated.
* **visualize_images(), visualize_landmarks(), visualize_landmarkgroups(), visualize_pointclouds()**: We now have a widget for all Menpo's objects. All widgets get a list of objects that can have different properties between them. They all have a _viewer options_ tab that specify options related to the _lines_, _markers_, _numbering_, _legend_, _axes_ and _figure_. Note that in tha case of a landmark group with multiple labels, the user can define a different colour per label.
* **features_selection()**: There is an additional widget that returns a function closure with the selected options (using `partial`). The widget needs to be updated with SIFT as soon as #495 is done. It has a preview tab in which the user can see the feature's effect on Lena's image. The widget is also defined in `menpo.feature.features.features_selection_widget()`.
* **Logo**: All widgets now have the Menpo logo!
* **Browser style**: There is an argument in all widgets that sets the browser of the passed-in objects (images, landmarks etc.) to have the form of +/- buttons or a slider. (@jalabort you might want to set `browser_style='slider'` whenever you call a widget! :) )

### Documentation
The PR fixes the documentation for `shape`, `landmark`, `image`, `visualize` and `math` packages.
In the future, we need to fix: `feature`, `io`, `model`, `transform` and `base`.

Let me know what you guys think!

### CODE REVIEW

**Comment by nontas** [comment]
I added some further changes to this PR, in order to be able to fix `menpofit`'s widgets. Specifically:

* **MatplotlibGraphPlotter** (and thus `GraphPlotter`) are now updated to accept a big list of rendering options related to the `lines`, `markers`, `legend`, `axes`, `grid` and `figure`. I suggest that you use this rendering class whenever you want to plot a graph (even with multiple curves), as it is much easier than using `matplotlib.pyplot` directly.

* Taking advantage of the `GraphPlotter` upgrade, I added **plot_eigenvalues()**, **plot_eigenvalues_ratio()** and **plot_eigenvalues_cumulative_ratio()** to the `PCAModel` class.

* The _viewer_options_ of all widgets now have an additional **image_options** tab (where applicable), which defines the `alpha` of the image and the `interpolation` technique. This allows to visualize an image as _pixelated_ which can be useful when rendering a low resolution model instance.

* Some code from `menpo.visualize.widgets.options` was only used by `menpofit`, so it is now moved to `menpofit.visualize.widgets.options` and deleted from here.

**Comment by nontas** [comment]
Menpofit's widgets are now fixed https://github.com/menpo/menpofit/pull/14 . So both PRs can get accepted as soon as everyone is happy. Please try to use a bit the widgets before accepting to make sure I didn't miss any obvious bug. Let me know what you guys think!

**Comment by nontas** [comment]
I think this is ready now! The view wrapper change by @patricksnape  and @jabooth  works perfectly and the widgets are fully upgraded with the introduced rendering options. 
https://github.com/menpo/menpofit/pull/14 can also be merged as soon as this one does.
+1

**Comment by patricksnape** [comment]
We think that this fine from our testing (@nontas and I). Therefore, we are going to pull this in to master so that everyone starts using it!

**Pull request merged**
