### PR TITLE
.view_widget() on LazyList to use menpowidgets to view items

### PR DESCRIPTION
**Pull request by jabooth**
It's increasingly common in Menpo to use `LazyList` to represent homogeneous collections of menpo objects, not only because LazyList is the default return type from menpo.io's multiple import, but also because `.map()` on these lists to derive further lazy data is a very powerful paradigm for exploratory scientific computing.

Viewing lazy list content with widgets typically looks like this currently:
```py
from menpowidgets import visualize_images
visualize_images(mio.import_images('./foo'))
```
whilst this is fine, it's a very common operation, and we can do better.

I've started exploratory work on menpowidgets to add a `visualize_list` convieniece function, that looks at the type of the first item in a list and invokes the most appropriate `visualize_foo` method on a list from this:
https://github.com/nontas/menpowidgets/blob/mm_widgets/menpowidgets/items.py
This PR, which has to wait for that change to land before it can be added, adds a simple `.view()` method to `LazyList` which simply invokes that function on the list if menpowidgets is installed. That means we can now express the above as:
```py
mio.import_images('./foo').view()
```
which is much more in-line with the usual menpo paradigm for object visualization.

### CODE REVIEW

**Comment by patricksnape** [comment]
Hmm - and heterogenous lists?

**Comment by jabooth** [comment]
@patricksnape I don't think that's really worth the complexity. It's very difficult to ensure that a lazy list is homogenous without loosing the lazy property (you'd have to execute all callables to determine their return type to really enforce the homogeneity constraint). 

You could say that for index callables we assume the type of the callable return is fixed, but this is still an assumption - the callable could behave differently for different index inputs.

I know this is a little gross, but I believe here the practical connivence trumps that. Thoughts?

**Comment by jabooth** [comment]
PS I guess I final option is a `HomogeneousLazyList` subclass that just adds this view method for now and potentially adds other things down the line, without really having any guarantee beyond us using it in our APIs when we know the callables are homogeneous (i.e. everywhere) but again I think that's an added complexity that users don't need. It's a learning curve as it is to explain to people what a lazy list is - at least for now it's a single unified type. Don't like the idea of making that story any more complex without very good reason...

**Comment by nontas** [comment]
I think we should call the method `.view_widget()` to be consistent with the rest of Menpo.

**Comment by jabooth** [comment]
@nontas yeah that's definitely fair. I think on another note it might be worth revisiting that pattern (kind of linked to #752), but totally agree for now it should be consistent so I'll change it.

**Comment by patricksnape** [comment]
I know what you're doing @jabooth, you sneaky rascal. You're just trying to sneak in your custom list types again...

**Comment by patricksnape** [comment]
Does this require anything else?

**Comment by jabooth** [comment]
@patricksnape it's just blocked on menpowidgets having the proposed `visualize_list` function - currently that's on a messy branch and @nontas is in the middle of fixing everything/moving it to ipywidgets 5.

**Comment by jabooth** [comment]
unblocked this now as we have menpowidgets released with the `view_widget` function.

Will merge after tests pass!

**Pull request merged**
