### PR TITLE
Add triangulation labels for ibug_face_(66/51/49)

### PR DESCRIPTION
**Pull request by jalabort**
This PR adds missing triangulation labels for the `ibug_face_66`, `ibug_face_51` and `ibug_face_49` annotation schemes.

### CODE REVIEW

**Comment by jabooth** [comment]
Looks good to me, will bring in tomorrow unless there are any objections. +1

**Comment by patricksnape** [comment]
I would like the doc generation to include these new methods

**Comment by patricksnape** [comment]
This was broken by the graph updates. Needs to be updated.

**Comment by jalabort** [comment]
This is now ready to be merged I believe.

**Comment by patricksnape** [comment]
OK :) +1

**Pull request merged**
