### PR TITLE
Graphs with isolated vertices

### PR DESCRIPTION
**Pull request by nontas**
This PR does the following:

- Changes all `Graph` and `PointGraph` definitions so that they take an `(n_vertces, n_vertices, )` `adjacency_matrix` rather than an `(n_edges, 2, )` `adjacency_list`. The `adjacency_matrix` is stored using `scipy.sparse.csr_matrix`.
- All `Graph` and `PointGraph` subclasses also have an `init_from_edges()` method that has the old functionality, i.e. constructing an instance by passing in the `adjacency_list` (now renamed to `edges`).
- Uses the functionality provided by `scipy.sparse.csgraph`. For example it replaces PADS minimum spanning tree with `scipy.sparse.csgraph.minimum_spanning_tree`.
- It makes sure that `PointUndirectedGraph` and `PointDirectedGraph` (and of course `UndirectedGraph` and `DirectedGraph` support the definition of isolated vertices, i.e. vertices with no edge connections. This is _not_ supported by `PointTree` (and `Tree`) as it doesn't make any sense.
- Updates all `graph.py` docs. The biggest change is that `PointGraph` is now removed from the docs as it shouldn't be used directly; only its `PointUndirectedGraph`, `PointDirectedGraph` and `PointTree` subclasses are useful.

### CODE REVIEW

**Comment by patricksnape** [comment]
I'm still seeing a guard for the `lfpw_face` landmarks that is preventing me from creating a graph with the isolated chin vertex.

**Comment by nontas** [comment]
The problem pointed out by @patricksnape was my bad. I fixed it, so now it's possible to create a graph with a single vertex (thus no edges). Note that it is still not possible to create a graph without any vertices; an exception is raised.

Does anyone else have any comments about this PR? I'd like to merge it as soon as possible...

**Comment by patricksnape** [comment]
This all looks great to me

**Comment by jabooth** [comment]
haven't had time to test this but looking through the code everything looks great, +1 from me

**Pull request merged**
