### PR TITLE
BREAKING: Imageio

### PR DESCRIPTION
**Pull request by patricksnape**
Add ImageIO importing and exporting. In particular, this adds methods for ``import_video``, ``import_videos`` and ``export_video``.

I have also moved most of the common image importing to freeimage as this is faster that pillow.

Breaking Changes:
  - Use ImageIO for things like `jpg` and `bmp`
  - GIF importer now uses ImageIO and thus returns `LazyList` rather than `list`
  - Bump to scipy 0.17.*

### CODE REVIEW

**Comment by patricksnape** [comment]
Jenkins is a liar - it's actually passing - @jabooth since you're at home, obviously bored, want to take a look at this as well? Maybe check it out and take it for a spin?

**Comment by patricksnape** [comment]
This is now on top of #669 and thus relies on that coming in. The history is also totally wrong because of me force pushing the HEAD - but I will do it again once LazyList comes in so that its just a single commit on top of master.

**Comment by patricksnape** [comment]
OK so the force push has now correctly merged.

**Comment by patricksnape** [comment]
jenkins, retest this please

**Comment by patricksnape** [comment]
@jabooth I think this is ready for you to check before coming in.

**Comment by patricksnape** [comment]
jenkins retest this please

**Comment by jabooth** [comment]
@patricksnape seems to be working great for me. LGTM, give us some time to test it out before release.

+1

**Pull request merged**
