### PR TITLE
Widgets for IPython3

### PR DESCRIPTION
**Pull request by nontas**
This PR changes all widgets, so that they:
* Are compatible with IPython 3.1.0
* Are defined as classes which makes them much easier to use (and the code is easier to read).

The major changes and improvements are:
* It is made sure that every widget change (trait value change) triggers only _one_ call of the render function. Until now, this wasn't the case, and sometimes a widget update (e.g. slider move) would call the render function multiple times. Thus, the widgets now are and feel faster.
* The styling of the widgets has now completely changed. They all have a `style` argument that can be set to `'coloured'` (default) or `'minimal'`. The `'coloured'` one employs colouring, border lines and a totally different design than before. The `'minimal'` theme is the same black and white style as before.
* All the new widget classes have `style()` and `predefined_style()` methods for styling the widget, `add_render_function()`, `remove_render_function()` and `replace_render_function()` for handling the rendering function and a `set_widget_state()` method for updating the state of the widget.
* All the basic widget components in `menpo.visualize.widgets.options` are now added to the docs.

Note that this PR should be merged along with https://github.com/menpo/menpofit/pull/31.

### CODE REVIEW

**Comment by patricksnape** [comment]
@nontas sign the contributors license agreement!

**Comment by jabooth** [comment]
@nontas looks good! few things:

Our builds are currently failing due to the new logo folder you have added to the menpo/data directory. I'm not sure if there are going to be other ramifications from this in terms of things like `menpo.io.import_builtin_assets`. We can sort this easily though.

You have the few checkboxes still to complete about notebooks - we can merge this in sooner and make a new issue on the menpo-notebooks repo to track that getting done.

Would be great to get all this brought in this week if we can!

**Comment by jalabort** [comment]
I'm with James, better to split this up, get it in, start using it and report possible bugs.

**Comment by patricksnape** [comment]
:open_mouth: Everything works! Lets get this in! +1

**Pull request merged**
