### PR TITLE
Quaternions for 3D Rotations

### PR DESCRIPTION
**Pull request by nontas**
This PR adds quaternion parametrization for 3D rotations. 

Specifically, it defines the `init_3d_from_quaternion()`, `_as_vector()`, `_from_vector_inplace()` of the `Rotation` class to support quaternions in case the object is 3-dimensional.

For more details on quaternions, refer to:
[Wheeler, M., and Katsushi I.. "Iterative Estimation of Rotation and Translation using the Quaternion", CMU-CS-95-215, 1995.](http://www.ri.cmu.edu/pub_files/pub1/wheeler_m_d_1995_1/wheeler_m_d_1995_1.pdf)

### CODE REVIEW

**Comment by patricksnape** [comment]
Why aren't we parameterizing the 2D rotations?

**Comment by jabooth** [comment]
@patricksnape only because we were time constrained and we only needed to solve for 3D parameterisation at this stage.

We could hold this up until we think through what to do for 2D parameterisations, but this is needed for 3DMM fitting in menpo3d, so we could do to move on it...happy for it to go in and raise an issue to add 2D params later?

**Comment by nontas** [comment]
I agree with @jabooth . Let's deal with 2D on a separate PR.

**Comment by patricksnape** [comment]
Can we make todos for that? And also, it would be good to have other init methods etc for different parameterisations e.g. from euler angles which are easier to reason about as a human (just make some issues?)

**Comment by jabooth** [comment]
We have an issue for Rotation convenience constructors, I'll link it to this PR:
https://github.com/menpo/menpo/issues/468

**Pull request merged**
