### PR TITLE
Add clip_pixels to Image and automatically clip RGB visualisations

### PR DESCRIPTION
**Pull request by grigorisg9gr**
Till now if the image is out of range, then the visualisation is weird. Such a case might appear in filtering or even with value scaling, e.g. 

```
import menpo.io as mio
im = mio.import_builtin_asset.lenna_png()
im.pixels *= 1.2
im.view()
```

This proposes one optional variable in the .view() methods to allow the clipping inside the image viewer (the original values are untouched).

### CODE REVIEW

**Comment by nontas** [comment]
Actually this issue is also discussed in https://github.com/menpo/menpo/issues/704.

The issue **only** applies in the case of RGB images. For example, first define this function:

```
%matplotlib inline
import menpo.io as mio
from menpo.feature import fast_dsift
import matplotlib.pyplot as plt

im = mio.import_builtin_asset.lenna_png()

def scale_pixel_range(im, channels=None):
    # Visualize original
    r = im.pixels_range()
    print("Original pixels: {:.2f}, {:.2f}".format(r[0], r[1]))
    plt.subplot(121)
    im.view(channels=channels)
    
    # Scale pixels
    im_scaled = im.copy()
    im_scaled.pixels *= 1.6
    im_scaled.pixels -= 2 * im_scaled.pixels.min()
    
    # Visualize scaled
    r = im_scaled.pixels_range()
    print("Scaled pixels: {:.2f}, {:.2f}".format(r[0], r[1]))
    plt.subplot(122)
    im_scaled.view(channels=channels)
```

Let's run it on the RGB image:
```
scale_pixel_range(im)
```
screenshot from 2016-11-23 19-13-48


Now on a greyscale image:
```
scale_pixel_range(im.as_greyscale())
```
screenshot from 2016-11-23 19-15-05


And final on a Dense DIFT image:
```
scale_pixel_range(fast_dsift(im), channels=0)
```
screenshot from 2016-11-23 19-16-35


So, given that it only affects the RGB images, I'm not sure what's the best approach. 

Maybe we should by default normalize the pixels inside `menpo.visualize.base.ImageViewer` in case we detect an RGB image that needs to be visualized as RGB (and not each channel separately). And then this could raise a warning that the pixels were actually rescaled. This channel check is already performed by the `_parse_channels()` method of `ImageViewer`. I don't really think that there should be a `check_value_range` argument, since it only applies for the RGB case.

**Comment by patricksnape** [comment]
Isn't this just Matplotlib behaving badly? Can't we see if there are options in matplotlib to make it behave better?

**Comment by grigorisg9gr** [comment]
Well, i had spent some time with trying to configure matplotlib as well, but the documentation is mostly for normalising the values (scaling them) rather than clipping them. 

There are the set_over and set_under methods, e.g. http://matplotlib.org/examples/pylab_examples/image_masked.html , http://stackoverflow.com/a/11386204/1716869 , but I didn't manage it to work well with rgb image and jet colourmap (or None as is the default).

**Comment by nontas** [comment]
I suggest we do the following. Add a `clip_pixels()` method in our `Image` class, similar to the `rescale_pixels()` one. Then, in case an image has 3 channels, we check if the pixels are in range ``[0, 1]`` and if they are not then we clip them and raise a warning.

What do you think?

**Comment by jabooth** [comment]
@nontas I think there is general utility in clipping pixels beyond just for visualisation, so I like adding `.clip_pixels()` to the API of `Image`. However we then use the new API or matplotlib directly to solve the clipping in the visualisation, I don't have strong feelings on (whatever is simplest/fastest/most reliable).

**Comment by nontas** [comment]
I forgot to mention that I had a look again and this issue cannot be solved with `matplotlib`. Specifically, the documentation of `matplotlib.imshow` mentions that this

```
norm = Normalize(vmin=0., vmax=1., clip=True)
plt.imshow(image, norm=norm, vmin=0, vmax=1)
```
should work, but it doesn't!

**Comment by patricksnape** [comment]
Fair enough! I can agree to clipping - be careful with types though.

**Comment by patricksnape** [comment]
Did we agree to change this to `clip_pixels`?

**Comment by nontas** [comment]
@grigorisg9gr do you agree?

**Comment by patricksnape** [comment]
@grigorisg9gr Sorry I missed that you updated this - does this fix your visualization issues?

**Comment by grigorisg9gr** [comment]
Yes it does. At least the issue reported here.

**Comment by patricksnape** [comment]
@jabooth Want to merge this before or after the dev tag?

**Comment by jabooth** [comment]
@patricksnape this can come in now it seems, looks fine to me?

@patricksnape go ahead and merge if you agree.

**Pull request merged**
