### PR TITLE
Extract patches types

### PR DESCRIPTION
**Pull request by patricksnape**
Adds the ability to extract patches from different type images:

  - ``np.float64``
  - ``np.float32``
  - ``np.uint8``

Also, adds passing of kwargs to ``import_builtin_asset`` so we can do:

    import menpo.io as mio
    bb = mio.import_builtin_asset.breakingbad_jpg(normalise=False)

And ``bb.pixels == np.uint8``

### CODE REVIEW

**Comment by patricksnape** [comment]
@jabooth OK with this?

**Comment by jalabort** [comment]
Can you add `np.uint8` to `gradient.pyx` in `features` as well? Seems sensible since images can be loaded as `np.uint8` and extract patches supports it...

**Comment by patricksnape** [comment]
What is the correct value of:

`` (100 - 1) / 2`` as a ``uint8``?

Is it ``0``, as it would be by default? Or ``50``, rounding up, or ``49`` rounding down?

**Comment by jalabort** [comment]
Mmm... Good point!

`0` does not seem a sensible answer to me... And `50` and `49` would not be consistent with other `menpo` transformations e.g. `image.as_greyscale(mode='average')`... What about simply returning `49.5` as `np.float64` which is exactly what happens when you call `image.as_greyscale(mode='average')` on image with `np.uint8` pixels (instead of crashing as it does now)?

**Comment by jalabort** [comment]
Get this in Patrick, we can deal with `integer gradient` in another PR.

**Pull request merged**
