### PR TITLE
Migrate towards LJSONv3.

### PR DESCRIPTION
**Pull request by grigorisg9gr**
This PR introduces the changes required for LJSONv3. Further details about this format can be found in here: https://github.com/menpo/landmarker.io/wiki/LEP-0001:-LJSON-v3 

This is not finished yet (check the to-do's below) , however this branch should already support several of the adaptations required. 
A part not yet implemented is that of the visibility masks for landmarks. (@jabooth)

TODO:
- [ ] Check the new documentation to correspond to the changes.
- [x] Add new tests for the import/export options added for LJSON.
- [ ] Finalise the visibility options and adapt the respective code.

### CODE REVIEW

**Comment by gabrielcowley** [comment]
I'm currently getting an error when running my `landmarkerio-server` instance (updated for ljsonv3 but not properly tested yet - [https://github.com/menpo/landmarkerio-server/pull/24](url)) against this PR in it's current state. The call to `menpo` occurs here: [https://github.com/gabrielcowley/landmarkerio-server/blob/c58afe3b5650cc0a79bd2b3ce441c9226a0b2c8b/landmarkerio/cache.py#L96](url).

The error occurs here: [https://github.com/grigorisg9gr/menpo/blob/88e39df044f642048a3c76a8f0e98cebc5ec5f21/menpo/io/input/base.py#L745](url). `lms` has no attribute `n_dims` here. This is because `_parse_ljson_v3` ([https://github.com/grigorisg9gr/menpo/blob/88e39df044f642048a3c76a8f0e98cebc5ec5f21/menpo/io/input/landmark.py#L355](url)) assigns a `PointCloud` as a 'member' of `lms` rather than as `lms` itself, so `lms` no longer has the attribute `n_dims`. I wasn't sure whether or not this was a known issue, but I thought I'd raise it.

**Comment by grigorisg9gr** [comment]
@gabrielcowley Thanks for reporting it. The last commit should fix this bug, however as discussed on Thursday, James' investigation in the expected behaviour with the resolver should be further discussed. 

However, this fix should allow you to temporary work with the new format.

**Comment by patricksnape** [comment]
I reverted the visibility stuff because I want to get this in - we can do it in a follow up - @jabooth can you confirm this works with landmarker.io?

**Comment by grigorisg9gr** [comment]
@patricksnape Ping for this, it would be quite useful.

**Pull request merged**
