### PR TITLE
Video importer docs and negative max_images

### PR DESCRIPTION
**Pull request by grigorisg9gr**
That is only ffmpeg is currently supported, avconv raises an error.

Additionally, minor fix in the multiple importers, since the max_{}
can get negative int values (does not return the last abs(max_{}) elements).

### CODE REVIEW

**Comment by patricksnape** [comment]
I'm not sure I understand your comment about the negative numbers?

**Comment by grigorisg9gr** [comment]
If you try to give max_images = -5 in import_images, it will import all but the last 5 or so, so it still works with negative int's.

**Comment by patricksnape** [comment]
Hmm well I'm not sure it's really designed to work that way. Perhaps that would be considered a bug...

**Comment by grigorisg9gr** [comment]
That's a different decision whether you would like to have it or not. 

However, currently in the code the command `filepaths = filepaths[:max_assets]`  in  _import_glob_lazy_list() works with both positive and negative.

**Comment by patricksnape** [comment]
Yes that is an unintended consequence of the Python slice syntax. Given the name of the argument and what it was intended to do in the first place this is a bug. For example, `max_*` implies you will load a maximum number of assets. If you have 100 items, and you pass `-2`, you will receive 98 items, **not** the last 2 items. So i'd rather check for this and throw a `ValueError`. Would be good if you could fix that here instead and then we can pull this in!

**Comment by patricksnape** [comment]
Thanks @grigorisg9gr!

**Pull request merged**
