### PR TITLE
Remove label kwarg

### PR DESCRIPTION
**Pull request by patricksnape**
Sorts out #614

### CODE REVIEW

**Comment by patricksnape** [comment]
@jabooth is this cool?

**Comment by jabooth** [comment]
+1 from me. Just a reminder that when it comes to writing the changelog for 0.6 we should try and document breaking changes, obviously dropping label is one, but include_mapping -> return_mapping should be documented as well.

**Comment by patricksnape** [comment]
The include_mapping -> return_mapping isn't a breaking change because I think that this is totally new unreleased behaviour anyway.

**Comment by jabooth** [comment]
@patricksnape cool my bad. (Side note, maybe a `CHANGELOG.md` file would be useful? As PRs come in if you do a breaking change as part of the the PR you add a line to the file? Can then be used for release docs etc?)

**Comment by patricksnape** [comment]
The release notes are already a changelog. I think maybe we should add BREAKING or something to PRs that break something? Then it is easy to grep for it?

**Comment by jabooth** [comment]
That's true, could just be a breaking GitHub tag that we start using?

Only reason I suggested a physical file is that at some point someone has to sit down and write a short English description of a breaking change and point to the PR. Doing that job at PR-time seems easier than at release-time? Also, there are sometimes multiple breaking changes per PR, and if possible I think it would he better to document them individually for the release notes. 

Maybe a better system than files would just be a gentleman so argreement that all breaking change PRs 1. Get the aforementioned breaking tag
2. Get a block at the top of the PR enumerating clearly the breaking API changes.

That way at release like you said it's easy to filter for breaking changes and just grab the descriptions.

**Pull request merged**
