### PR TITLE
SIFT features

### PR DESCRIPTION
**Pull request by nontas**
This PR adds dense SIFT features using `cyvlfeat`. The default values are set so that the output descriptor has length of 36 channels (same as HOG features) and not 128 which is the default from VLfeat. Also, the function has a `fast` flag which is enabled by default. 

Just for future reference, SIFT features are about 5x faster (3x if `fast` is `False`) compared to HOG features on my machine, using of course the exact same parameters.

I also added two SIFT-related tests and made some fixes on the feature functions' documentation.

### CODE REVIEW

**Comment by nontas** [comment]
As soon as this gets in, https://github.com/menpo/menpo-notebooks/pull/25 should be merged as well.

**Comment by patricksnape** [comment]
This is finally passing - I am weeping with joy

**Comment by jabooth** [comment]
Anything holding this up now @patricksnape @nontas? Or are we merging? We might need a little merge party when this finally goes in...

**Comment by jalabort** [comment]
Can I add my `fast_dsift` to `predifined` before this is merged in? So everyone can run the new AAMs straight away?

**Comment by jabooth** [comment]
Sure @jalabort, that sounds sensible to me

**Comment by nontas** [comment]
The reshape of the features returned by vlfeat was wrong. Now it's fixed thanks to @patricksnape and @jabooth . This is ready _at last_ after the tests pass

**Pull request merged**
