### PR TITLE
(WIP): first attempt at bumping to MPL2

### PR DESCRIPTION
**Pull request by jabooth**
Following #781, this PR attempts to move to MPL v2:
http://matplotlib.org/users/whats_new.html

For now we will see how the test suite does across all platforms.

### CODE REVIEW

**Comment by patricksnape** [comment]
# Matplotlib 1.5
Matplotlib 1.5
# Matplotlib 2.0
Matplotlib 2.0


Clearly something is amiss

**Comment by patricksnape** [comment]
Also, the **actual** problem with this is that Matplotlib >=1.5.3 (including 2.0) brings with it a dependency on QT 5 which is not compatible with Mayavi 😢 So we actually can't upgrade right now until someone takes the time to make Mayavi work with QT 5

**Comment by jabooth** [comment]
So that's blocked on two PRs:

https://github.com/enthought/traitsui/pull/242
https://github.com/enthought/pyface/pull/171

Heartening to see work has been underway a long time, but looks like it's been stale for a little while.

**Comment by patricksnape** [comment]
Having said that, this output looks really weird so would be good to diagnose what is happening

**Comment by patricksnape** [comment]
Fixed by #811

**Pull request closed without merging**
